namespace Gym_Platform_V1.data.DTOs.GymOwner
{
    /// <summary>
    /// Data Transfer Object for GymOwner response.
    /// Contains only non-sensitive information.
    /// Password and PasswordHash are intentionally excluded for security.
    /// </summary>
    public class GymOwnerResponseDto
    {
        /// <summary>
        /// Gets or sets the unique identifier for the gym owner.
        /// Auto-generated by database.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the full name of the gym owner.
        /// </summary>
        public string? FullName { get; set; }

        /// <summary>
        /// Gets or sets the username of the gym owner.
        /// </summary>
        public string? UserName { get; set; }

        /// <summary>
        /// Gets or sets the email address of the gym owner.
        /// </summary>
        public string? Email { get; set; }

        /// <summary>
        /// Gets or sets the phone number of the gym owner.
        /// </summary>
        public string? PhoneNumber { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the gym owner was created.
        /// Set automatically by database (GETUTCDATE()).
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the gym owner account is active.
        /// Newly created accounts default to true.
        /// </summary>
        public bool IsActive { get; set; }

        // NOTE: Password and PasswordHash are intentionally NOT included in response
        // These sensitive fields are never returned to client for security reasons
    }
}
