namespace Gym_Platform_V1.DTOs.MembershipPlan
{
    // Client-provided data only. OwnerId comes from the JWT, and Id/CreatedAt
    // are generated by the server, so none of them appear here.
    public class CreateMembershipPlanRequestDto
    {
        public int GymId { get; set; }
        public string? Name { get; set; }
        public decimal Price { get; set; }
        public int DurationInDays { get; set; }
        public bool IsSessionBased { get; set; }
        public int NumberOfSessions { get; set; }
    }
}
