using Gym_Platform_V1.Abstractions.Interfaces;
using Gym_Platform_V1.DTOs.GymOwner;
using Gym_Platform_V1.DTOs.GymOwnerApplication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Gym_Platform_V1.Controllers
{
    /// <summary>
    /// Controller for all Admin operations.
    /// Covers GymOwner management and GymOwner application review.
    /// Only Admin users can access these endpoints.
    /// </summary>
    [ApiController]
    [Route("api/admin")]
    [Authorize(Roles = "Admin")]
    public class AdminController : ControllerBase
    {
        private readonly IGymOwnerService _gymOwnerService;
        private readonly IGymOwnerApplicationService _applicationService;
        private readonly ILogger<AdminController> _logger;

        public AdminController(
            IGymOwnerService gymOwnerService,
            IGymOwnerApplicationService applicationService,
            ILogger<AdminController> logger)
        {
            _gymOwnerService = gymOwnerService ?? throw new ArgumentNullException(nameof(gymOwnerService));
            _applicationService = applicationService ?? throw new ArgumentNullException(nameof(applicationService));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        // ============================================
        // GYM OWNER MANAGEMENT
        // ============================================

        /// <summary>
        /// Creates a new GymOwner.
        ///
        /// Business Rules:
        /// - Username must be unique globally
        /// - Email must be unique globally and valid format
        /// - Phone must be unique globally
        /// - Password will be hashed using BCrypt
        /// - New GymOwner starts with IsActive = true
        /// - CreatedAt auto-generated by database
        /// </summary>
        /// <param name="request">GymOwner creation request with details</param>
        /// <returns>
        /// 201 Created: GymOwner successfully created with response DTO
        /// 400 Bad Request: Validation failed (invalid DTO or model state)
        /// 401 Unauthorized: JWT missing, invalid, or expired
        /// 403 Forbidden: Authenticated but not Admin
        /// 409 Conflict: Duplicate username, email, or phone
        /// 500 Internal Server Error: Unexpected server error
        /// </returns>
        [HttpPost("gym-owners/create")]
        [ProducesResponseType(typeof(GymOwnerResponseDto), StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status401Unauthorized)]
        [ProducesResponseType(StatusCodes.Status403Forbidden)]
        [ProducesResponseType(StatusCodes.Status409Conflict)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<GymOwnerResponseDto>> CreateGymOwner([FromBody] CreateGymOwnerRequestDto request)
        {
            try
            {
                _logger.LogInformation("Received valid GymOwner creation request for username: {Username}", request.UserName);

                var response = await _gymOwnerService.CreateAsync(request);

                _logger.LogInformation("GymOwner created successfully with ID: {GymOwnerId}", response.Id);

                // Return 201 Created with Location header
                return CreatedAtAction(nameof(GetGymOwnerById), new { id = response.Id }, response);
            }
            catch (InvalidOperationException ex)
            {
                // Business validation failed (duplicate username, email, or phone)
                _logger.LogWarning(ex, "Business validation failed during GymOwner creation");

                // Determine which type of conflict it is
                string message = ex.Message;
                if (message.Contains("already taken") || message.Contains("already registered") || message.Contains("already in use"))
                {
                    return Conflict(new
                    {
                        message = ex.Message
                    });
                }

                // Generic invalid operation
                return BadRequest(new
                {
                    message = ex.Message
                });
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError(ex, "Argument null error during GymOwner creation");
                return BadRequest(new
                {
                    message = "Invalid request data"
                });
            }
            catch (DbUpdateException ex)
            {
                // Database error (unlikely if uniqueness validations passed above)
                _logger.LogError(ex, "Database error during GymOwner creation - possible race condition");
                return StatusCode(StatusCodes.Status500InternalServerError, new
                {
                    message = "An error occurred while creating the GymOwner. Please try again.",
                    traceId = HttpContext.TraceIdentifier
                });
            }
            catch (Exception ex)
            {
                // Unexpected exception
                _logger.LogError(ex, "Unexpected error during GymOwner creation");
                return StatusCode(StatusCodes.Status500InternalServerError, new
                {
                    message = "An unexpected error occurred",
                    traceId = HttpContext.TraceIdentifier
                });
            }
        }

        /// <summary>
        /// Retrieves all GymOwners.
        ///
        /// Business Rules:
        /// - Returns summary list of all GymOwners
        /// - Does not load Gym entities or details
        /// - Returns empty array if no GymOwners exist (200 OK, not 404)
        /// - This is a read-only operation (no database modification)
        /// </summary>
        /// <returns>
        /// 200 OK: List of GymOwnerResponseDto (may be empty array)
        /// 401 Unauthorized: JWT missing, invalid, or expired
        /// 403 Forbidden: Authenticated but not Admin
        /// 500 Internal Server Error: Unexpected server error
        /// </returns>
        [HttpGet("gym-owners")]
        [ProducesResponseType(typeof(IEnumerable<GymOwnerResponseDto>), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status401Unauthorized)]
        [ProducesResponseType(StatusCodes.Status403Forbidden)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<IEnumerable<GymOwnerResponseDto>>> GetAllGymOwners()
        {
            try
            {
                _logger.LogInformation("Retrieving all GymOwners");

                var response = await _gymOwnerService.GetAllAsync();

                _logger.LogInformation("Retrieved {Count} GymOwners total", (response as List<GymOwnerResponseDto>)?.Count ?? 0);

                // Return 200 OK with list (even if empty)
                return Ok(response);
            }
            catch (Exception ex)
            {
                // Unexpected exception
                _logger.LogError(ex, "Unexpected error retrieving all GymOwners");
                return StatusCode(StatusCodes.Status500InternalServerError, new
                {
                    message = "An unexpected error occurred",
                    traceId = HttpContext.TraceIdentifier
                });
            }
        }

        /// <summary>
        /// Retrieves a GymOwner by their unique identifier with all related Gyms.
        ///
        /// Business Rules:
        /// - Id must be greater than 0
        /// - Returns BadRequest if id is invalid (id &lt;= 0)
        /// - Returns NotFound if GymOwner does not exist
        /// - Includes all Gyms owned by this GymOwner
        /// - This is a read-only operation (no database modification)
        /// </summary>
        /// <param name="id">The unique identifier of the GymOwner to retrieve</param>
        /// <returns>
        /// 200 OK: GymOwner found with response DTO and all related Gyms
        /// 400 Bad Request: Id is invalid (id &lt;= 0)
        /// 401 Unauthorized: JWT missing, invalid, or expired
        /// 403 Forbidden: Authenticated but not Admin
        /// 404 Not Found: GymOwner does not exist
        /// 500 Internal Server Error: Unexpected server error
        /// </returns>
        [HttpGet("gym-owners/{id}")]
        [ProducesResponseType(typeof(GymOwnerDetailsDto), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status401Unauthorized)]
        [ProducesResponseType(StatusCodes.Status403Forbidden)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<GymOwnerDetailsDto>> GetGymOwnerById(int id)
        {
            try
            {
                _logger.LogInformation("Retrieving GymOwner with ID: {GymOwnerId}", id);

                if (id <= 0)
                {
                    _logger.LogWarning("Invalid GymOwner ID provided: {GymOwnerId}", id);
                    return BadRequest(new
                    {
                        message = "GymOwner ID must be greater than 0"
                    });
                }

                var response = await _gymOwnerService.GetByIdAsync(id);

                if (response == null)
                {
                    _logger.LogInformation("GymOwner not found with ID: {GymOwnerId}", id);
                    return NotFound(new
                    {
                        message = $"GymOwner with id {id} not found"
                    });
                }

                _logger.LogInformation("GymOwner retrieved successfully - ID: {GymOwnerId}, Gyms Count: {GymsCount}", id, response.Gyms.Count);
                return Ok(response);
            }
            catch (Exception ex)
            {
                // Unexpected exception
                _logger.LogError(ex, "Unexpected error retrieving GymOwner with ID: {GymOwnerId}", id);
                return StatusCode(StatusCodes.Status500InternalServerError, new
                {
                    message = "An unexpected error occurred",
                    traceId = HttpContext.TraceIdentifier
                });
            }
        }

        // ============================================
        // GYM OWNER APPLICATION MANAGEMENT
        // ============================================

        /// <summary>
        /// Get all GymOwner applications.
        /// </summary>
        [HttpGet("gym-owner-applications")]
        [ProducesResponseType(typeof(IEnumerable<GymOwnerApplicationResponseDto>), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status401Unauthorized)]
        [ProducesResponseType(StatusCodes.Status403Forbidden)]
        public async Task<ActionResult<IEnumerable<GymOwnerApplicationResponseDto>>> GetAllApplications()
        {
            try
            {
                var list = await _applicationService.GetApplicationsAsync();
                return Ok(list);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Unexpected error retrieving applications");
                return StatusCode(StatusCodes.Status500InternalServerError, new { message = "An unexpected error occurred", traceId = HttpContext.TraceIdentifier });
            }
        }

        /// <summary>
        /// Get all pending GymOwner applications.
        /// </summary>
        [HttpGet("gym-owner-applications/pending")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status401Unauthorized)]
        [ProducesResponseType(StatusCodes.Status403Forbidden)]
        public async Task<IActionResult> GetPendingApplications()
        {
            var applications =
                await _applicationService.GetPendingApplicationsAsync();

            return Ok(applications);
        }

        /// <summary>
        /// Approve a pending application.
        /// </summary>
        [HttpPost("gym-owner-applications/{id}/approve")]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status401Unauthorized)]
        [ProducesResponseType(StatusCodes.Status403Forbidden)]
        public async Task<IActionResult> ApproveApplication(int id)
        {
            try
            {
                await _applicationService.ApproveApplicationAsync(id);
                return NoContent();
            }
            catch (KeyNotFoundException ex)
            {
                _logger.LogWarning(ex, "Application not found for approval: {Id}", id);
                return NotFound(new { message = ex.Message });
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogWarning(ex, "Invalid operation during approval: {Id}", id);
                return BadRequest(new { message = ex.Message });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Unexpected error approving application: {Id}", id);
                return StatusCode(StatusCodes.Status500InternalServerError, new { message = "An unexpected error occurred", traceId = HttpContext.TraceIdentifier });
            }
        }

        /// <summary>
        /// Reject a pending application with a reason.
        /// </summary>
        [HttpPost("gym-owner-applications/{id}/reject")]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status401Unauthorized)]
        [ProducesResponseType(StatusCodes.Status403Forbidden)]
        public async Task<IActionResult> RejectApplication(int id, [FromBody] RejectApplicationRequestDto request)
        {
            try
            {
                await _applicationService.RejectApplicationAsync(id, request.RejectionReason);
                return NoContent();
            }
            catch (KeyNotFoundException ex)
            {
                _logger.LogWarning(ex, "Application not found for rejection: {Id}", id);
                return NotFound(new { message = ex.Message });
            }
            catch (InvalidOperationException ex)
            {
                _logger.LogWarning(ex, "Invalid operation during rejection: {Id}", id);
                return BadRequest(new { message = ex.Message });
            }
            catch (ArgumentException ex)
            {
                _logger.LogWarning(ex, "Invalid rejection request for: {Id}", id);
                return BadRequest(new { message = ex.Message });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Unexpected error rejecting application: {Id}", id);
                return StatusCode(StatusCodes.Status500InternalServerError, new { message = "An unexpected error occurred", traceId = HttpContext.TraceIdentifier });
            }
        }
    }
}
