using Gym_Platform_V1.Abstractions.Interfaces;
using Gym_Platform_V1.DTOs.GymOwner;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Gym_Platform_V1.Controllers
{
    /// <summary>
    /// Controller for GymOwner management operations.
    /// Provides endpoints for creating and managing gym owners.
    /// Only Admin users can access these endpoints.
    /// </summary>
    [ApiController]
    [Route("api/gym-owners")]
    [Authorize(Roles = "Admin")]
    public class GymOwnerController : ControllerBase
    {
        private readonly IGymOwnerService _gymOwnerService;
        private readonly ILogger<GymOwnerController> _logger;

        /// <summary>
        /// Initializes a new instance of the GymOwnerController class.
        /// </summary>
        /// <param name="gymOwnerService">Service for GymOwner operations</param>
        /// <param name="logger">Logger for diagnostic and error logging</param>
        /// <exception cref="ArgumentNullException">Thrown if service or logger is null</exception>
        public GymOwnerController(IGymOwnerService gymOwnerService, ILogger<GymOwnerController> logger)
        {
            _gymOwnerService = gymOwnerService ?? throw new ArgumentNullException(nameof(gymOwnerService));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Creates a new GymOwner.
        /// 
        /// Authorization: Only Admin users can create gym owners
        /// 
        /// Business Rules:
        /// - Username must be unique globally
        /// - Email must be unique globally and valid format
        /// - Phone must be unique globally
        /// - Password will be hashed using BCrypt
        /// - New GymOwner starts with IsActive = true
        /// - CreatedAt auto-generated by database
        /// 
        /// Validation:
        /// - DTO validation (required fields, format, length)
        /// - Business validation (uniqueness checks)
        /// - Database constraints (unique indexes as safety net)
        /// </summary>
        /// <param name="request">GymOwner creation request with details</param>
        /// <returns>
        /// 201 Created: GymOwner successfully created with response DTO
        /// 400 Bad Request: Validation failed (invalid DTO or model state)
        /// 401 Unauthorized: JWT missing, invalid, or expired
        /// 403 Forbidden: Authenticated but not Admin
        /// 409 Conflict: Duplicate username, email, or phone
        /// 500 Internal Server Error: Unexpected server error
        /// </returns>
        [HttpPost("create")]
        [ProducesResponseType(typeof(GymOwnerResponseDto), StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status401Unauthorized)]
        [ProducesResponseType(StatusCodes.Status403Forbidden)]
        [ProducesResponseType(StatusCodes.Status409Conflict)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<GymOwnerResponseDto>> Create([FromBody] CreateGymOwnerRequestDto request)
        {
            try
            {
            
                _logger.LogInformation("Received valid GymOwner creation request for username: {Username}", request.UserName);

                // ============================================
                // STEP 2: CALL SERVICE
                // ============================================
                var response = await _gymOwnerService.CreateAsync(request);

                _logger.LogInformation("GymOwner created successfully with ID: {GymOwnerId}", response.Id);

                // ============================================
                // STEP 3: RETURN CREATED RESPONSE (201)
                // ============================================
                // Return 201 Created with Location header
                return CreatedAtAction(nameof(GetById), new { id = response.Id }, response);
            }
            catch (InvalidOperationException ex)
            {
                // Business validation failed (duplicate username, email, or phone)
                _logger.LogWarning(ex, "Business validation failed during GymOwner creation");

                // Determine which type of conflict it is
                string message = ex.Message;
                if (message.Contains("already taken") || message.Contains("already registered") || message.Contains("already in use"))
                {
                    return Conflict(new
                    {
                        message = ex.Message
                    });
                }

                // Generic invalid operation
                return BadRequest(new
                {
                    message = ex.Message
                });
            }
            catch (ArgumentNullException ex)
            {
                _logger.LogError(ex, "Argument null error during GymOwner creation");
                return BadRequest(new
                {
                    message = "Invalid request data"
                });
            }
            catch (DbUpdateException ex)
            {
                // Database error (unlikely if uniqueness validations passed above)
                _logger.LogError(ex, "Database error during GymOwner creation - possible race condition");
                return StatusCode(StatusCodes.Status500InternalServerError, new
                {
                    message = "An error occurred while creating the GymOwner. Please try again.",
                    traceId = HttpContext.TraceIdentifier
                });
            }
            catch (Exception ex)
            {
                // Unexpected exception
                _logger.LogError(ex, "Unexpected error during GymOwner creation");
                return StatusCode(StatusCodes.Status500InternalServerError, new
                {
                    message = "An unexpected error occurred",
                    traceId = HttpContext.TraceIdentifier
                });
            }
        }

        /// <summary>
        /// Retrieves a GymOwner by their unique identifier.
        /// 
        /// Authorization: Only Admin users can retrieve gym owners
        /// 
        /// Business Rules:
        /// - Id must be greater than 0
        /// - Returns BadRequest if id is invalid (id <= 0)
        /// - Returns NotFound if GymOwner does not exist
        /// - This is a read-only operation (no database modification)
        /// </summary>
        /// <param name="id">The unique identifier of the GymOwner to retrieve</param>
        /// <returns>
        /// 200 OK: GymOwner found with response DTO
        /// 400 Bad Request: Id is invalid (id <= 0)
        /// 401 Unauthorized: JWT missing, invalid, or expired
        /// 403 Forbidden: Authenticated but not Admin
        /// 404 Not Found: GymOwner does not exist
        /// 500 Internal Server Error: Unexpected server error
        /// </returns>
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(GymOwnerResponseDto), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status401Unauthorized)]
        [ProducesResponseType(StatusCodes.Status403Forbidden)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<GymOwnerResponseDto>> GetById(int id)
        {

            try { 
                _logger.LogInformation("Retrieving GymOwner with ID: {GymOwnerId}", id);

                // ============================================
                // STEP 2: CALL SERVICE
                // ============================================
                var response = await _gymOwnerService.GetByIdAsync(id);

                // ============================================
                // STEP 3: RETURN RESPONSE
                // ============================================
                if (response == null)
                {
                    _logger.LogInformation("GymOwner not found with ID: {GymOwnerId}", id);
                    return NotFound(new
                    {
                        message = $"GymOwner with id {id} not found"
                    });
                }

                _logger.LogInformation("GymOwner retrieved successfully - ID: {GymOwnerId}", id);
                return Ok(response);
            }
            catch (Exception ex)
            {
                // Unexpected exception
                _logger.LogError(ex, "Unexpected error retrieving GymOwner with ID: {GymOwnerId}", id);
                return StatusCode(StatusCodes.Status500InternalServerError, new
                {
                    message = "An unexpected error occurred",
                    traceId = HttpContext.TraceIdentifier
                });
            }
        }
    }
}
